basic_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: prompts/basic_search_system_prompt.txt
cache:
  storage:
    base_dir: cache
    type: file
  type: json
chunking:
  encoding_model: o200k_base
  overlap: 100
  size: 1200
  type: tokens
cluster_graph:
  max_cluster_size: 10
community_reports:
  completion_model_id: default_completion_model
  graph_prompt: prompts/community_report_graph.txt
  max_input_length: 8000
  max_length: 2000
  text_prompt: prompts/community_report_text.txt
completion_models:
  default_completion_model:
    api_base: https://retrieve7sf2ai.cognitiveservices.azure.com/
    api_version: 2025-04-01-preview
    auth_method: azure_managed_identity
    azure_deployment_name: gpt-4.1
    model: gpt-4.1
    model_provider: azure
    retry:
      type: exponential_backoff
drift_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: prompts/drift_search_system_prompt.txt
  reduce_prompt: prompts/drift_search_reduce_prompt.txt
embed_text:
  embedding_model_id: default_embedding_model
embedding_models:
  default_embedding_model:
    api_base: https://retrieve7sf2ai.cognitiveservices.azure.com/
    api_version: 2025-04-01-preview
    auth_method: azure_managed_identity
    azure_deployment_name: text-embedding-3-large
    model: text-embedding-3-large
    model_provider: azure
    retry:
      type: exponential_backoff
extract_claims:
  completion_model_id: default_completion_model
  description: Claims or facts relevant to information discovery.
  enabled: false
  max_gleanings: 1
  prompt: prompts/extract_claims.txt
extract_graph:
  completion_model_id: default_completion_model
  entity_types:
  - organization
  - person
  - geo
  - event
  - policy
  - regulation
  max_gleanings: 1
  prompt: prompts/extract_graph.txt
extract_graph_nlp:
  text_analyzer:
    extractor_type: regex_english
global_search:
  completion_model_id: default_completion_model
  knowledge_prompt: prompts/global_search_knowledge_system_prompt.txt
  map_prompt: prompts/global_search_map_system_prompt.txt
  reduce_prompt: prompts/global_search_reduce_prompt.txt
input:
  file_pattern: .*\.md
  type: text
input_storage:
  base_dir: C:/Users/nabilahmed/Documents/Code/retrieve-ui/corpus
  type: file
local_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: prompts/local_search_system_prompt.txt
output_storage:
  base_dir: output
  type: file
reporting:
  base_dir: logs
  type: file
snapshots:
  embeddings: false
  graphml: false
summarize_descriptions:
  completion_model_id: default_completion_model
  max_length: 500
  prompt: prompts/summarize_descriptions.txt
vector_store:
  db_uri: output/lancedb
  type: lancedb
